# Generated by Django 5.0.7 on 2024-08-06 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('brand', models.CharField(max_length=150, verbose_name='Бренд')),
                ('image', models.ImageField(upload_to='media/images/', verbose_name='Изображение')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание объекта')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кол-во товаров')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма к оплате')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Заказ в обработке'), (2, 'Заказ оплачен'), (3, 'Заказ отменен')], default=1, verbose_name='Статус')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание объекта')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('order_comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.cosmetic', verbose_name='Косметика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
