# Generated by Django 5.0.7 on 2024-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во товара'),
        ),
    ]
